version: 2.1
jobs:
  build-lint:
    docker:
      - image: circleci/python:3.7.3-stretch
    steps:
      - checkout
      - run:
          name: "Create, make and lint code"
          command: |
            python3 -m venv venv
            . venv/bin/activate
            echo "== Setup required .env file =="
            touch .env
            echo "#.env" >> ".env"
            echo FLASK_APP=app.py >> ".env"
            echo FLASK_DEBUG=True >> ".env"
            echo API_KEY=$API_KEY >> ".env"
            echo "== Sanity check of .env file =="
            cat .env
            echo "== Run make =="
            make install
            echo "== Download hadolint =="
            sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            sudo chmod +x /bin/hadolint
            echo "== Checking for hadolint =="
            hadolint -v
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: "Run lint"
          command: |
            . venv/bin/activate
            make lint
  
  docker-build-test-upload:
    docker:
      - image: cimg/go:1.17
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Create .env file with project env variable API_KEY"
          command: |
            echo "== Setup required .env file =="
            touch .env
            echo "#.env" >> ".env"
            echo FLASK_APP=app.py >> ".env"
            echo FLASK_DEBUG=True >> ".env"
            echo API_KEY=$API_KEY >> ".env"
            echo "== Sanity check of .env file =="
            cat .env
      - run:
          name: "Docker Login, build and tag"
          command: |
            echo "== Login to docker with envirvonment variables =="
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            echo "== Build docker image =="
            docker build --tag=udacitycapstone .
            echo "== Check for image =="
            docker image ls --filter=reference='udacitycapstone'
      - run:
          name: "Test Docker image"
          command: |
            echo "== Launch image locally =="
            docker run -d -p 5000:5000 capstone
            export APPTEST=$(curl -L -s http://127.0.0.1:5000 | grep '<title>Udacity Capstone</title>')
            if [ -z "$APPTEST" ]
            then
              echo "== Docker image failure, investigate and fix =="
            else
              echo "== Docker image webpage load successful =="
              curl -s --head http://127.0.0.1:5000
            fi
      - run:
          name: "Tag & Push image to dockerhub"
          command: |
            echo "== Tag docker image for upload =="
            docker tag udacitycapstone $DOCKERHUB_USERNAME/udacitycapstone
            echo "== Upload docker image =="
            docker push $DOCKERHUB_USERNAME/udacitycapstone

  aws-setup:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: "Install tar, gzip & wget packages"
          command: |
            yum install -y tar gzip wget
      - run:
          name: "Ensure AWS ECR exists"
          command: |
            echo "== Check AWS user =="
            aws sts get-caller-identity
            echo "== Check variables =="
            echo "ECR Repository Name: ${ECR_REPO_NAME}"
            echo "== Run check and create if missing =="
            echo "aws ecr create-repository --region "${AWS_DEFAULT_REGION}" --repository-name "${ECR_REPO_NAME}" !!!"
            export ECRCHECK=$(aws ecr describe-repositories --region "${AWS_DEFAULT_REGION}" --repository-names "${ECR_REPO_NAME}")
            if [ -z "$ECRCHECK" ]
            then
              echo "== Target ECR Not found! Creating required ECR... =="
              aws ecr create-repository --region "${AWS_DEFAULT_REGION}" --repository-name "${ECR_REPO_NAME}"
            else
              echo "== Target ECR Found, OK to proceed =="
            fi
      - run:
          name: "Download eksctl"
          command: |
            echo "== Check version and download if missing =="
            export EKSCTLCHECK=$(eksctl version)
            if [ -z "$EKSCTLCHECK" ]
            then
              echo "== eksctl not found, downloading =="
              wget https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_Linux_amd64.tar.gz
              echo "== create temp folder =="
              mkdir eksctl
              echo "== extract the download =="
              tar -xf eksctl_Linux_amd64.tar.gz -C ./eksctl
              echo "== move eksctl to bin =="
              mv ./eksctl/eksctl /usr/local/bin
              echo "== check version =="
              eksctl version
            else
              echo "== eksctl found =="
              eksctl version
            fi
      - run:
          name: "Download kubectl"
          command: |
            echo "== Check version and download if missing =="
            export KUBECTLCHECK=$(kubectl version --short --client | grep 'Client Version' | awk '{print $3}')
            if [ -z "$KUBECTLCHECK" ]
            then
              echo "== kubectl not found, downloading =="
              curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
              echo "== install kubectl =="
              install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
              echo "== check version =="
              kubectl version --short --client | grep 'Client Version' | awk '{print $3}'
            else
              echo "== kubectl found =="
              kubectl version --short --client | grep 'Client Version' | awk '{print $3}'
            fi
      - run:
          name: "Confirm EKS cluster - deploy cluster if none found"
          no_output_timeout: 30m
          command: |
            echo "== Checking for eks cluster =="
            export ExistingCluster=($(aws eks list-clusters --output text | grep cluster | awk '{print $2}'))
            echo $ExistingCluster
            if [[ "$ExistingCluster" == *cluster ]]
            then
              echo "== Cluster Found =="
            else
              echo "== Check AWS user after getting previous failure =="
              aws sts get-caller-identity
              echo "== No Cluster Found =="
              echo "Building cluster"
              eksctl create cluster -f eksyml/cluster.yml
            fi
#         Need to add if neither exist, then create one            
#      - run:
#          name: "Test cleanup of LastCluster"
#          no_output_timeout: 30m
#          command: |
#            echo "== Checking for Last Cluster =="
#            echo "Last Cluster Deployed:" ${LastCluster}
#            echo "== Cleanup and remove old EKS Cluster =="
#            if [[ "$LastCluster" == *blue ]]
#            then
#              eksctl delete cluster -f eksyml/bluecluster.yml
#            elif [[ "$LastCluster" == *green ]]
#            then
#              eksctl delete cluster -f eksyml/greencluster.yml
#            fi

#            ## Next line would configure kubectl
#            aws eks update-kubeconfig --region ${AWS_DEFAULT_REGION} --name ${NewCluster}

#            echo "== List eks clusters =="
#            aws eks list-clusters
#            echo "== Check eksctl version =="
#            eksctl version
#            echo "== Get clusters =="
#            eksctl get cluster

workflows:
  default:
    jobs:
      - build-lint
      - docker-build-test-upload:
          requires: [build-lint]
      - aws-setup:
          requires: [docker-build-test-upload]