apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: "udacitycapstone-blue"
  region: us-east-1b

nodeGroups:
  - name: "worker-group-blue"
    instanceType: t2.micro
    minSize: 1
    maxSize: 2
    desiredCapacity: 2