apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: "udacitycapstone-cluster"
  region: us-east-1

nodeGroups:
  - name: "worker-group"
    instanceType: t2.micro
    minSize: 1
    maxSize: 2
    desiredCapacity: 2