apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacitycapstone-green
  namespace: udacitycapstone-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udacitycapstone-green
  template:
    metadata:
      labels:
        app: udacitycapstone-green
    spec:
      containers:
      - name: udacitycapstone-green
        image: danwyllie/udacitycapstone:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: udacitycapstone-green
  namespace: udacitycapstone-green
spec:
  type: LoadBalancer
  selector:
    app: udacitycapstone-green
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000