apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacitycapstone-green
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udacitycapstone-green
  template:
    metadata:
      labels:
        app: udacitycapstone-green
    spec:
      containers:
      - name: udacitycapstone-green
        image: danwyllie/udacitycapstone:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000